### PR TITLE
added a new constraint Gravity Particles

### PR DESCRIPTION
**Pull request by harsh-dev0**
I made these particles interact with each other just like how planets interact in space. You know, like how Earth orbits around the Sun because of gravity? Yup, something like that! But instead of planets, we've got these colorful dots.

### CODE REVIEW

**Comment by anonthedev** [comment]
why is there a ```initializeGravityParticles()``` function in the script.js file?

**Comment by anonthedev** [comment]
can't you keep it out of script.js? Similar to how other constraints are being done?

**Comment by harshpa324** [comment]
`initializeGravityParticles()` was just there to setup the limit of number of particles, I can move it to gravity particle constraint

**Comment by anonthedev** [comment]
I don't think you need this function in utils.js

```export function createParticle(x, y, vx, vy, mass, color) {
  return {
    x: x,          // X coordinate
    y: y,          // Y coordinate
    vx: vx,        // Velocity in the X direction
    vy: vy,        // Velocity in the Y direction
    mass: mass,    // Mass of the particle
    color: color   // Color of the particle
  };
}```

you can edit the already existing ```particle``` function in utils.js and make it have mass, and edit the ```create``` function with a default mass of 0 or 1 whatever.

**Comment by harshpa324** [comment]
I tried doing that but due to
 `export function create(number, color, particles, vx = 0, vy = 0) {
  let group = [];
  for (let i = 0; i < number; i++) {
    group.push(particle(random(), random(), color, vx, vy));
    particles.push(group[i]);
  }
  return group;
}` 
being used in rest two constraints, rest two stop working as there is no mass parameter in rest of the constraint

**Comment by harshpa324** [comment]
I just added mass to create by assigning mass to 0. Then it started working again

**Comment by anonthedev** [comment]
why is the default value of mass different for ```create``` and ```particle``` functions?

**Comment by harshpa324** [comment]
I didn't notice but default value of mass don't matter, if you want I can edit it

**Comment by anonthedev** [comment]
yeah just edit it, otherwise it might cause confusions

**Comment by harshpa324** [comment]
Fixed it

**Comment by anonthedev** [comment]
thanks for this constraint, merging now.

**Comment by harsh-dev0** [comment]
Thanks, enjoyed this

**Pull request merged**
