### PR TITLE
Boids

### PR DESCRIPTION
**Pull request by anuraglodhi**

### CODE REVIEW

**Comment by anuraglodhi** [comment]
This PR adds a new constraint to the list which simulates flocking behavior of bird using algorithm described by Craig Reynolds which can be found here: [Boids - Wikipedia](https://en.wikipedia.org/wiki/Boids)

**Comment by anuraglodhi** [comment]
https://github.com/anonthedev/particleLife/assets/32013268/ff0140fe-8b5e-4da2-b475-d906f7e8a14b

**Comment by anonthedev** [comment]
awesome PR man just add some comment in the utils.js last function

**Comment by anuraglodhi** [comment]
@anonthedev I added the comments. You can merge now. Tell me if you want something changed.

**Comment by anonthedev** [comment]
merging now, thanks for the PR man

**Comment by anuraglodhi** [comment]
Found this repo in the apna college PR spam thread on X. Thought I should give it a try.

**Comment by anonthedev** [comment]
Glad you did

**Pull request merged**
